ERROR: Unable to locate a modulefile for 'cudatoolkit'
/u/mi3se/anaconda3/envs/crypten/lib/python3.8/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA A16 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A16 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
NVIDIA A16
Using cuda backend.
Shape: Train data torch.Size([60000, 28, 28]), test data torch.Size([10000, 28, 28]).
Traceback (most recent call last):
  File "benchmark.py", line 215, in <module>
    train_loss, train_time = train(model, device, train_loader, optimizer, epoch, criterion)
  File "benchmark.py", line 158, in train
    output = model(data)
  File "/u/mi3se/anaconda3/envs/crypten/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "benchmark.py", line 122, in forward
    x = self.conv1(x)
  File "/u/mi3se/anaconda3/envs/crypten/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/mi3se/anaconda3/envs/crypten/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/u/mi3se/anaconda3/envs/crypten/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
